package com.example.infotech.clasespojo;

public enum MenuItems{
    Componentes,
    PlacasBase,
    Procesadores,
    DiscosDuros,
    FuentesDeAlimentacion,
    TarjetasGraficas,
    MemoriasRam,
    TarjetasDeSonido,
    LectoresDeDiscos,
    Ordenadores,
    Sobremesa,
    Portatiles,
    Gaming,
    AllInOne,
    Smartphones,
    Redes,
    Routers,
    TarjetasRed,
    CableRed,
    Antenas,
    AdaptadoresUsb,
    Consolas,
    PlayStation,
    Xbox,
    Nintendo,
}